const ROLES = {
    SUPER_ADMIN: "SUPER_ADMIN",
    BRANCH_ADMIN: "BRANCH_ADMIN",
    COUNSELOR: "COUNSELOR",
    FRONT_DESK: "FRONT_DESK",
    TEACHER: "TEACHER",
    REFERRAL_AGENT: "REFERRAL_AGENT",
    STUDENT: "STUDENT",
};

const PIPELINE_STAGES = {
    LEAD: "LEAD",
    PROSPECT: "PROSPECT",
    ENROLLED: "ENROLLED",
    APPLIED: "APPLIED",
    OFFER_RECEIVED: "OFFER_RECEIVED",
    VISA_APPLIED: "VISA_APPLIED",
    VISA_APPROVED: "VISA_APPROVED",
    DEPARTED: "DEPARTED",
    LOST: "LOST",
};

module.exports = { ROLES, PIPELINE_STAGES };
